
config.vm.define "ar-kali-{{config.general.key_name}}-{{config.general.attack_range_name}}" do |config|
    VM_NAME_KALI= "attack-range-kali"
    config.vm.box = "kalilinux/rolling"
    config.vm.boot_timeout = 600
    config.vm.hostname = "kali"
    config.vm.network :private_network, ip: "10.0.1.30"
    config.ssh.password = "vagrant"
  
    config.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "#{VM_NAME_KALI}"
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "1"]
    end

    config.vm.provider "vmware_desktop" do |v, override|
      v.vmx["displayname"] = "#{VM_NAME_KALI}"
      v.memory = 2048
      v.cpus = 1
      v.gui = true
    end

  end